drop database if exists POKEMONS ;
create database POKEMON;

CREATE TABLE POKEMON(
ID SERIAL PRIMARY KEY,
NOM char(12) NOT NULL,
TIPUS char(12) NULL,
ATACS text[]
);

INSERT INTO POKEMON (NOM, TIPUS, ATACS)  VALUES ('POKEMON1', 'TIPUS1' , '{ATAC1, ATAC2, ATAC3}');
INSERT INTO POKEMON  (NOM, TIPUS, ATACS) VALUES ('POKEMON2', 'TIPUS2' , '{ATAC1, ATAC2, ATAC3}');
INSERT INTO POKEMON  (NOM, TIPUS, ATACS) VALUES ('POKEMON3', 'TIPUS3' , '{ATAC1, ATAC2, ATAC3}');
INSERT INTO POKEMON  (NOM, TIPUS, ATACS) VALUES ('POKEMON4', 'TIPUS4' , '{ATAC1, ATAC2, ATAC3}');
INSERT INTO POKEMON  (NOM, TIPUS, ATACS) VALUES ('POKEMON5', 'TIPUS5' , '{ATAC1, ATAC2, ATAC3}');
